name: Build Kubectl
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - kubectl/**
env:
  DOCKER_NAMESPACE: mystery0
  SERVICE_NAME: kubectl
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest kubectl version
        id: get_version
        run: |
          VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          echo "Latest version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Download kubectl binary
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "Downloading kubectl $VERSION for linux/amd64..."
          cd kubectl
          curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/amd64/kubectl"
          ls -lh kubectl
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: kubectl
          file: kubectl/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.SERVICE_NAME }}:${{ steps.get_version.outputs.version }}
            ${{ env.DOCKER_NAMESPACE }}/${{ env.SERVICE_NAME }}:latest